USE [master]
GO

/****** Object:  Database [bd_site]    Script Date: 10/01/2021 19:53:08 ******/
IF OBJECT_ID('bd_site', 'u') IS NOT NULL 
DROP DATABASE [bd_site]
GO

/****** Object:  Database [bd_site]    Script Date: 10/01/2021 19:53:08 ******/
CREATE DATABASE [bd_site]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [bd_site].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [bd_site] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [bd_site] SET ANSI_NULLS ON 
GO
ALTER DATABASE [bd_site] SET ANSI_PADDING ON 
GO
ALTER DATABASE [bd_site] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [bd_site] SET ARITHABORT OFF 
GO
ALTER DATABASE [bd_site] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [bd_site] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [bd_site] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [bd_site] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [bd_site] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [bd_site] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [bd_site] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [bd_site] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [bd_site] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [bd_site] SET  ENABLE_BROKER 
GO
ALTER DATABASE [bd_site] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [bd_site] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [bd_site] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [bd_site] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [bd_site] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [bd_site] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [bd_site] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [bd_site] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [bd_site] SET  MULTI_USER 
GO
ALTER DATABASE [bd_site] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [bd_site] SET DB_CHAINING OFF 
GO
ALTER DATABASE [bd_site] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [bd_site] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [bd_site] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [bd_site] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [bd_site] SET QUERY_STORE = OFF
GO
ALTER DATABASE [bd_site] SET  READ_WRITE 
GO


